GET http://localhost:3000

###
GET http://localhost:3000/songs/?page=1&limit=2
# GET http://localhost:3000/songs/

###
GET http://localhost:3000/songs/1

###
POST http://localhost:3000/songs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyaWFuYUBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoxLCJpYXQiOjE3Mzg3MzExNTMsImV4cCI6MTczODgxNzU1M30.rPO6XnZqMlWdQ3nY8n9wkkQNP5KzbMIh9PTjvjmfzMM
Content-Type: application/json

{
    "title" : "positions",
    "artists" : [1],
    "releasedDate" : "2023-05-29",
    "duration" : "02:34",
    "lyrics":"minnna minnnaa"
}


###
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
    "title" : "lasting lover",
    "artists" : [1],
    "releasedDate" : "2022-09-29",
    "duration" : "02:34",
    "lyrics":"minnna minnnaa"
}

###
DELETE http://localhost:3000/songs/3

### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Monkey D.",
    "lastName": "Luffy",
    "email": "luffy@gmail.com",
    "password": "123456"
}

### login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "ariana@gmail.com",
    "password": "123456"
}


### profile

GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyaWFuYUBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImlhdCI6MTczODczMDgyMCwiZXhwIjoxNzM4ODE3MjIwfQ.nNdg23XW3ZpNWPvUzUqaP3-S6wfwt6Us0Z5JTsthEVM

### enable 2FA

GET http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyaWFuYUBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImFydGlzdElkIjoxLCJpYXQiOjE3Mzg3NDk2NzksImV4cCI6MTczODgzNjA3OX0.BZmSlukGTCyVc4Pg1B14RbJQ6S07pKaBKdl_e9h83t4

### validate 2FA token
POST  http://localhost:3000/auth/validate-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyaWFuYUBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImlhdCI6MTczODczMDgyMCwiZXhwIjoxNzM4ODE3MjIwfQ.nNdg23XW3ZpNWPvUzUqaP3-S6wfwt6Us0Z5JTsthEVM
Content-Type: application/json

{
    "token":"579722"
}

### disable 2FA

GET http://localhost:3000/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyaWFuYUBnbWFpbC5jb20iLCJ1c2VySWQiOjIsImlhdCI6MTczODczMDgyMCwiZXhwIjoxNzM4ODE3MjIwfQ.nNdg23XW3ZpNWPvUzUqaP3-S6wfwt6Us0Z5JTsthEVM


### Access profile with apikey
GET http://localhost:3000/auth/profile
Authorization: Bearer 5c29eff5-ccfe-4d28-9639-8aa3361d441e


### create playlist

POST http://localhost:3000/playlists
Content-Type: application/json
{
    "name":"myplaylist",
    "songs":[
        1
    ],
    "user":1
}